// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbb7sIV2GojAADPyyBIGVJHYh0gQvvu3I',
    appId: '1:834698191366:web:07ab225f6498352fff5987',
    messagingSenderId: '834698191366',
    projectId: 'todo-app-f53c1',
    authDomain: 'todo-app-f53c1.firebaseapp.com',
    storageBucket: 'todo-app-f53c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSE3jdrELvQhTrwzv4o-HJwsVtabJUBrA',
    appId: '1:834698191366:android:258efdef22f8c1f0ff5987',
    messagingSenderId: '834698191366',
    projectId: 'todo-app-f53c1',
    storageBucket: 'todo-app-f53c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN-GFpdpbx8sBQT1pI29zxPZhFZ1mG52E',
    appId: '1:834698191366:ios:79453a101b1614c3ff5987',
    messagingSenderId: '834698191366',
    projectId: 'todo-app-f53c1',
    storageBucket: 'todo-app-f53c1.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN-GFpdpbx8sBQT1pI29zxPZhFZ1mG52E',
    appId: '1:834698191366:ios:79453a101b1614c3ff5987',
    messagingSenderId: '834698191366',
    projectId: 'todo-app-f53c1',
    storageBucket: 'todo-app-f53c1.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbb7sIV2GojAADPyyBIGVJHYh0gQvvu3I',
    appId: '1:834698191366:web:2471e5a1f3811ccfff5987',
    messagingSenderId: '834698191366',
    projectId: 'todo-app-f53c1',
    authDomain: 'todo-app-f53c1.firebaseapp.com',
    storageBucket: 'todo-app-f53c1.appspot.com',
  );
}
